apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVURxOVhxUUNiODB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1qRXdOakUwTVRCYUZ3MHpOakEwTVRnd05qRTVNVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURJb0Z4Q3dKSTdHV3VRS2h4NU54S1E3b25vekYySWlBRVcrbmUzb2FKZkR4UGpXbDNDNllybEd6d28KRlIyU0NQVG4rMEVCZDZJeUozR2ZPRDlRY0JZb085UUgwWWo0Q1Z5SzZJT2FIU3V1L2VzekhyOGdvTVREeXk2ZApKV3ZqcHkyL3hzK09qREtyVFlpaHFJTVdWN2gwcTRwM3VJRzlFSndKWXdydHJwOTZqT0FUWHVNdWFTTUhuRklMCkxJQSsrUjJCeHREbjlsMkNUV1BZc0Z6Q1gwWHYvejhQdlRVT1NrR1VHWWhDbmhxY29DbmpYVTBRVTBJUURqeEEKL3J0K3VvTGw1R3Y5emFINkhmRGkrZ3ZQQlJmTTR6dElXK2RSRWNyQ2NsTVNTc1N6RnlTaHNJeVV5Um1TdFNjUQp1UUloTjhwZGFKZXhXVzVVQmJURlB2SHl1Yzg5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSjYxZmt4UE1SZjFtVWo5blNoZFpzdlp3TmlUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnIzMUNMNU45ZQpvNEY0azdnT3F3OVFmRFdJTHRpZjFFYVBjMnVjTVJucWlkZW54RXNobjkrN2hON1BpeDVLOXY0dWVkRmlpUThXCnVwTFNpdXV1V05INmV1RnJSR3dCOGZ0azg5d1g1RVZUb0lzcTFoOVZtaFBwYXdKU3ovNXFTOTMyN1ByTnBldWwKdTVNYkVtZWJQR3lJcjFBQVlOQVllUThJdDZpeEZCdTRGSURienA1SmZmb0VJcE1WZm05MEQ4M0ZmUHMxWTg0QgpFYmJ5YlVIUkNnbnJLSXd5cFJGRGdGSmVQbzlhYzFaUTVqd005cmcwc29tdHQ2RElXRkh5NnF5N0dXMVdpNlVHCnQrKytyYXJxZkRoR2hIYzJUSXNibHBJbWJodEM2OWl4YVphMnJmQkl5OTdyc2g2dW9Ia1J4VHFBemxHekxWUEMKQlNBcTFEcVhvOStSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5616B0ACFACBC0FFC3DF6FA14E60EF27.yl4.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:768571909004:cluster/shopwave-eks
contexts:
- context:
    cluster: arn:aws:eks:ap-south-1:768571909004:cluster/shopwave-eks
    user: arn:aws:eks:ap-south-1:768571909004:cluster/shopwave-eks
  name: arn:aws:eks:ap-south-1:768571909004:cluster/shopwave-eks
current-context: arn:aws:eks:ap-south-1:768571909004:cluster/shopwave-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-south-1:768571909004:cluster/shopwave-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - shopwave-eks
      - --output
      - json
      command: aws
