apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: shopwave

data:
  default.conf: |
    server {
      listen 80;

      location /api/users {
        proxy_pass http://auth:3001;
      }

      location /api/products {
        proxy_pass http://product:3002;
      }

      location /api/orders {
        proxy_pass http://order:3003;
      }

      location /api/payments {
        proxy_pass http://payment:3004;
      }

      location /api/notifications {
        proxy_pass http://notification:3005;
      }
    }