apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: shopwave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

        # 🔥 IMPORTANT FIX
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf   # ✅ MUST

      volumes:
      - name: nginx-config
        configMap:
          name: api-gateway-config