apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: shopwave
data:
  default.conf: |
    server {
      listen 80;

      location /api/users {
        proxy_pass http://auth:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /api/products {
        proxy_pass http://product:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /api/orders {
        proxy_pass http://order:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /api/payments {
        proxy_pass http://payment:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /api/notifications {
        proxy_pass http://notification:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }