apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: shopwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: nginx
        ports:
        - containerPort: 80
        