apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: shopwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: nginx
        ports:
        - containerPort: 80