apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: shopwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: nginx
        ports:
        - containerPort: 80