apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: shopwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: 768571909004.dkr.ecr.ap-south-1.amazonaws.com/shopwave-product:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017