apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: shopwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: 768571909004.dkr.ecr.ap-south-1.amazonaws.com/shopwave-product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/shopwave"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"